// NOTE: html2pdf.js is lazy-loaded inside downloadPdf so the PDF stack
// stays out of the initial bundle.

function slugify(s: string): string {
  return (
    s
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 50) || "report"
  );
}

const PDF_CSS = `
  .pdf-doc { font-family: Inter, Arial, sans-serif; color: #0f172a; line-height: 1.65; font-size: 13px; }
  .pdf-doc h1 { font-size: 22px; margin: 0 0 12px; }
  .pdf-doc h2 { font-size: 17px; margin: 18px 0 8px; }
  .pdf-doc h3 { font-size: 14px; margin: 14px 0 6px; }
  .pdf-doc p { margin: 8px 0; }
  .pdf-doc ul, .pdf-doc ol { margin: 8px 0; padding-left: 22px; }
  .pdf-doc li { margin: 3px 0; }
  .pdf-doc blockquote { border-left: 3px solid #c7d2fe; margin: 10px 0; padding: 4px 12px; color: #475569; }
  .pdf-doc code { background: #f1f5f9; padding: 1px 5px; border-radius: 4px; font-size: 12px; }
  .pdf-doc pre { background: #0f172a; color: #f1f5f9; padding: 12px; border-radius: 8px; overflow-x: auto; }
  .pdf-doc pre code { background: none; color: inherit; padding: 0; }
  .pdf-doc table { border-collapse: collapse; width: 100%; margin: 10px 0; font-size: 12px; }
  .pdf-doc th, .pdf-doc td { border: 1px solid #cbd5e1; padding: 6px 8px; text-align: left; }
  .pdf-doc th { background: #eef2ff; }
  .pdf-doc a { color: #4f46e5; }
  .pdf-doc hr { border: none; border-top: 1px solid #e2e8f0; margin: 14px 0; }
  .pdf-meta { color: #64748b; font-size: 11px; margin-bottom: 14px; }
`;

// Minimal markdown -> HTML for PDF/print (screen rendering stays ReactMarkdown).
function markdownToHtml(markdown: string): string {
  const escaped = markdown
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

  const inline = (s: string) =>
    s
      .replace(/`([^`]+)`/g, "<code>$1</code>")
      .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
      .replace(/(^|\W)\*([^*\n]+)\*/g, "$1<em>$2</em>")
      .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>');

  const lines = escaped.split("\n");
  const out: string[] = [];
  let listOpen: "ul" | "ol" | null = null;
  const closeList = () => {
    if (listOpen) {
      out.push(listOpen === "ul" ? "</ul>" : "</ol>");
      listOpen = null;
    }
  };

  for (const raw of lines) {
    const line = raw.trim();
    if (!line) {
      closeList();
      continue;
    }
    if (line.startsWith("### ")) {
      closeList();
      out.push(`<h3>${inline(line.slice(4))}</h3>`);
    } else if (line.startsWith("## ")) {
      closeList();
      out.push(`<h2>${inline(line.slice(3))}</h2>`);
    } else if (line.startsWith("# ")) {
      closeList();
      out.push(`<h1>${inline(line.slice(2))}</h1>`);
    } else if (line.startsWith("&gt; ")) {
      closeList();
      out.push(`<blockquote>${inline(line.slice(5))}</blockquote>`);
    } else if (/^(-|\*) /.test(line)) {
      if (listOpen !== "ul") {
        closeList();
        out.push("<ul>");
        listOpen = "ul";
      }
      out.push(`<li>${inline(line.replace(/^(-|\*) /, ""))}</li>`);
    } else if (/^\d+\. /.test(line)) {
      if (listOpen !== "ol") {
        closeList();
        out.push("<ol>");
        listOpen = "ol";
      }
      out.push(`<li>${inline(line.replace(/^\d+\. /, ""))}</li>`);
    } else if (/^(-{3,}|\*{3*})$/.test(line)) {
      closeList();
      out.push("<hr/>");
    } else {
      closeList();
      out.push(`<p>${inline(raw.trim())}</p>`);
    }
  }
  closeList();
  return out.join("");
}

function buildPdfElement(title: string, markdown: string): HTMLDivElement {
  const el = document.createElement("div");
  el.innerHTML =
    `<style>${PDF_CSS}</style>` +
    `<div class="pdf-doc">` +
    `<h1>${title.replace(/</g, "&lt;")}</h1>` +
    `<div class="pdf-meta">Generated by Deep Research Engine · ${new Date().toLocaleString()}</div>` +
    markdownToHtml(markdown) +
    `</div>`;
  return el;
}

export async function downloadPdf(markdown: string, title: string) {
  // Lazy-load the heavy PDF stack only when the user actually exports.
  const { default: html2pdf } = await import("html2pdf.js");
  const name = `${slugify(title)}.pdf`;
  html2pdf()
    .set({
      margin: 12,
      filename: name,
      image: { type: "jpeg", quality: 0.95 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: "mm", format: "a4", orientation: "portrait" },
    })
    .from(buildPdfElement(title, markdown))
    .save();
}

export function downloadMarkdown(markdown: string, title: string) {
  const blob = new Blob([markdown], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${slugify(title)}.md`;
  a.click();
  URL.revokeObjectURL(url);
}

export async function copyText(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

export function wordCount(markdown: string): number {
  return markdown.trim().split(/\s+/).filter(Boolean).length;
}
